import sys


def ErrorHandler(_funcName):
    print(_funcName + 'is getting error!')
    sys.exit(-1)

